<a href="https://colab.research.google.com/github/tejask-42/Speech-Emotion-Recognition-Project/blob/main/Week_1/NumPy_Assignment_WiDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Assignment

This assignment will introduce you to the NumPy library and demonstrate how vectorization can significantly accelerate computations compared to traditional iterative approaches.

You are to only write/modify the code in between consecutive # < START > and # < END > comments. DO NOT modify other parts of the notebook.

**Start by running the below cell, to import the NumPy library.**

In [ ]:
import numpy as np

### Initialising arrays
NumPy offers multiple methods to create and populate arrays, one of them is using the `np.array()` function.

Create the following matrix with the variable arr : $$ \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix} $$

In [ ]:
# < START >
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# < END >

print(arr)
print("Shape: ", arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)


You can also transpose arrays (same as with matrices), but a more general and commonly used function is the `array.reshape()` function

Now create a new array arr_transpose which is transpose of the upper triangular matrix including the diagonal of the above matrix. The upper triangular matrix is the matrix with all elements below the diagonal equal to zero.

In [ ]:
# < START >
arr_transpose = np.transpose(np.triu(arr))
# < END >

print(arr_transpose)
print("Shape: ", arr_transpose.shape)

[[1 0 0]
 [2 5 0]
 [3 6 9]]
Shape:  (3, 3)


`reshape` is commonly used to flatten data stored in multi-dimensional arrays (ex: a 2D array representing a B/W image)

Create a new array arr_flat that contains the same elements as arr but has been flattened to a column array

`array.flatten()` converts it into a row array

In [ ]:
# < START >
arr_flatten = arr.flatten().reshape(-1, 1)
# < END >

print(arr_flatten)
print("Shape: ", arr_flatten.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape:  (9, 1)


A few more basic methods to initialize arrays exist.

- Initialize a NumPy array RANDOM_ARR of dimensions $2 \times 3$ with random values.  Do not use the values of the dimensions directly, instead use the variables provided as arguments. Hint  : `np.random.randn()`

In [ ]:
# random array
n_rows = 2
n_cols = 3

# < START >
RANDOM_ARR = np.random.randn(n_rows, n_cols)
# < END >

print("RANDOM_ARR: ", RANDOM_ARR)

RANDOM_ARR:  [[ 0.20069567 -0.14560605  1.79187152]
 [-0.7645036  -0.51443258  2.58638285]]


- Create a new array ZERO_ARR of dimensions $2 \times 1 \times 2$ whose every element is 0

In [ ]:
# zeros array
# < START >
ZERO_ARR = np.zeros((2, 1, 2))
# < END >

print("ZERO_ARR: ", ZERO_ARR)

ZERO_ARR:  [[[0. 0.]]

 [[0. 0.]]]


- Initialize an array ONE_ARR of dimensions $2 \times 1 \times 2$ whose every element is 1

In [ ]:
# ones array
# < START >
ONE_ARR = np.ones((2, 1, 2))
# < END >

print("ONES_ARR: ", ONE_ARR)

ONES_ARR:  [[[1. 1.]]

 [[1. 1.]]]


### Multiplying two matrices
Matrix multiplication is a binary operation that produces a matrix from two matrices. For matrix multiplication, the number of columns in the first matrix must be equal to the number of rows in the second matrix.

`np.dot()` is used to compute the dot product of two arrays. It behaves differently for arrays of different dimensions.


- Now, initialise two 1-D arrays A_1 and B_1 of size $3$ with random integers (search a function for integer random numbers in NumPy). Multiply the two arrays and store the result in a new array C_1.

In [ ]:
# < START >
A = np.random.randint(10, size=3)
B = np.random.randint(10, size=3)
C = np.dot(A, B)
# < END >

assert A.shape == (3,)
assert B.shape == (3,)
# The line above is an assert statement, which stops the program execution if the specified condition evaluates to False.
# Assert statements are commonly used in neural network programs to verify that the matrices have the correct dimensions.

print("A: ", A)
print("B: ", B)
print("C: ", C)

A:  [2 7 8]
B:  [1 8 9]
C:  130


- In the next step, initialise two 2-D arrays A_2 and B_2 of dimensions $3 \times 3$ with random integers. Multiply the two arrays and store the result in a new array C_2.

In [ ]:
# < START >
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = np.dot(A, B)
# < END >

assert A.shape == (3,3)
assert B.shape == (3,3)

print("A: ", A)
print("B: ", B)
print("C: ", C)

A:  [[9 9 5]
 [2 1 2]
 [8 6 6]]
B:  [[0 9 5]
 [3 7 5]
 [7 7 8]]
C:  [[ 62 179 130]
 [ 17  39  31]
 [ 60 156 118]]


- In the last step, initialise two 3-D arrays A_3 and B_3 of dimensions $2 \times 2 \times 2$ with random integers. Multiply the two arrays and store the result in a new array C_3.

In [ ]:
# < START >
A = np.random.randint(10, size=(2, 2, 2))
B = np.random.randint(10, size=(2, 2, 2))
C = np.dot(A, B)
# < END >

assert A.shape == (2,2,2)
assert B.shape == (2,2,2)

print("A: ", A)
print("B: ", B)
print("C: ", C)

A:  [[[9 4]
  [3 8]]

 [[1 6]
  [6 6]]]
B:  [[[0 3]
  [2 5]]

 [[3 9]
  [7 8]]]
C:  [[[[  8  47]
   [ 55 113]]

  [[ 16  49]
   [ 65  91]]]


 [[[ 12  33]
   [ 45  57]]

  [[ 12  48]
   [ 60 102]]]]


### Indexing and Slicing
Indexing and slicing are fundamental techniques for accessing and manipulating elements of an array. Indexing is used to obtain individual elements, while slicing allows you to obtain a subset of the array.

**Indexing** retrieves specific elements of an array. In one-dimensional arrays, you use the index position. For multidimensional arrays, elements can be accessed using either `array[i][j]` or `array[i, j]`, where the latter is preferred. The `array[i, j]` notation is more efficient because it avoids creating a temporary intermediate array when resolving the first index, directly retrieving the desired element. This efficiency extends to higher-dimensional arrays, where elements can be accessed across multiple dimensions, e.g., `array[i, j, k]`.

**Slicing** extracts portions of an array using the syntax `array[start:end:step]`.
- `start`: Specifies where the slice begins (inclusive)
- `end`: Specifies where the slice ends (exclusive)
- `step`: Determines the interval between indices

By default, `start` is `0`, `end` is the length of the array, and `step` is `1`. Slicing can be applied independently across dimensions in multidimensional arrays, separated by commas (e.g., `array[start:end, start:end]`). Importantly, slicing creates a view of the original array, meaning changes to the slice will reflect in the original array. If indices are out of bounds, slicing returns an empty array instead of raising an error.
<br>

*Phew! That was a lot of information. Let's put it to practice.*

- Initialise an array x with values 1 to 10.
    - Create a new array y that contains the first three elements of x.
    - Create a new array z that contains the last two elements of x.
    - Create a new array w that contains all the elements of x except the first and last element.
    - Create a new array v with alternate elements of x starting from the first element.

In [ ]:
# < START >
x = np.arange(1, 11)
y = x[:3]
z = x[-2:]
w = x[1:-1]
v = x[::2]
# < END >

print("y: ", y)
print("z: ", z)
print("w: ", w)
print("v: ", v)

y:  [1 2 3]
z:  [ 9 10]
w:  [2 3 4 5 6 7 8 9]
v:  [1 3 5 7 9]


- Initialise a 2-D array X as follows: $$ \begin{bmatrix}
4 & 5 & 2 \\
3 & 7 & 9 \\
1 & 4 & 5 \\
6 & 6 & 1
\end{bmatrix} $$
    - Create a new array Y using X, that is of the form [[4, 5], [1, 4]].
    - Create a new array Z using X, that is of the form [[5, 2], [7, 9], [4, 5]].


In [ ]:
# < START >
X = np.array([[4, 5, 2], [3, 7, 9], [1, 4, 5], [6, 6, 1]])
Y = X[0:3:2, :2]
Z = X[:-1, 1:]
# < END >

print("X: ", X)
print("Y: ", Y)
print("Z: ", Z)

X:  [[4 5 2]
 [3 7 9]
 [1 4 5]
 [6 6 1]]
Y:  [[4 5]
 [1 4]]
Z:  [[5 2]
 [7 9]
 [4 5]]


### Broadcasting
Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. Frequently, we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
Broadcasting allows this by automatically expanding the smaller array to match the shape of the larger one, making the operation possible without explicitly reshaping the arrays. This feature enhances flexibility in array operations, enabling highly efficient algorithms while minimizing memory usage.

It's important to note that broadcasting is distinct from matrix multiplication or padding; it specifically refers to how NumPy handles arrays of different shapes during arithmetic operations.


- Initialise an array x with values 1 to 4.
    - Create a new array y using x, that is of the form [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]].
    - Create a new array z using x, that is of the form [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]].
    - Implement broadcasting to add the arrays x and z and store the result in a new array w.

In [ ]:
# < START >
x = np.arange(1, 5)
y = np.array([x, x, x])
z = np.transpose(np.array([x, x, x, x]))
w = x + z

# < END >

print("x: ", x)
print("y: ", y)
print("z: ", z)
print("w: ", w)

x:  [1 2 3 4]
y:  [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
z:  [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
w:  [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


- Initialise a 2-D array X as follows: $$ \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix} $$
    - Create a new array Y using X, that is of the form [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]].
    - Create a new array Z using X, that is of the form [[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]].
    - Multiply each element of the first row of X by 4 and each element of the second row of X by 5. Store the result in a new array W. Hint : Make an array of the form [4, 5] and use broadcasting.

In [ ]:
# < START >
X = np.arange(1, 13).reshape(4, 3)
Y = np.array([X[0], X[0], X[0], X[0]])
temp = X.flatten()[:4]
Z = np.stack((temp, temp, temp), axis=1)
W = X * np.array([4, 5, 1, 1]).reshape(-1, 1)
# < END >

print("X: ", X)
print("Y: ", Y)
print("Z: ", Z)
print("W: ", W)

X:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y:  [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
Z:  [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
W:  [[ 4  8 12]
 [20 25 30]
 [ 7  8  9]
 [10 11 12]]


### Vectorization
Vectorization is the process of transforming an algorithm to operate on a set of values (a vector) simultaneously, rather than processing each value individually. This eliminates the need for explicit loops, leading to more concise, readable, and efficient code. Vectorized code is typically faster than non-vectorized code because it leverages optimized, low-level implementations in C.

To highlight the benefits of vectorization, let's compare the execution times of a non-vectorized approach with a vectorized one, where the task is to multiply each element of a 2D array by 3.

- Create a 2-D array `arr_nonvectorised` of dimensions $1000 \times 1000$ with random integers. Multiply each element of the array by 3 using a non-vectorized approach and store the result in a new array Y. Calculate the time taken to perform this operation.
- Create a copy of the original array `arr_nonvectorised` and store it in a new array `arr_vectorised`. Multiply each element of the array by 3 using a vectorized approach and store the result in a new array Z. Calculate the time taken to perform this operation.

And u can see the difference in time taken by both the approaches.

In [ ]:
import time

# Initialise both the aarays
# < START >
arr_nonvectorised = np.random.randint(10, size=(1000, 1000))
arr_vectorised = arr_nonvectorised.copy()
# < END >

start_nv = time.time()

# Non-vectorized approach
# < START >
Y = np.zeros((1000, 1000))
for i in range(1000):
  for j in range(1000):
    Y[i, j] = arr_nonvectorised[i, j] * 3
# < END >

end_nv = time.time()

print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")


start_v = time.time()

# Vectorized approach
# < START >
Z = arr_vectorised * 3
# < END >

end_v = time.time()

print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")


# Uncomment and run the following line to verify that both approaches are achieving the same result.
# print("Non-vectorized array: ", Y)
# print("Vectorized array: ", Z)

Time taken in non-vectorized approach: 620.0330257415771 ms
Time taken in vectorized approach: 4.271984100341797 ms


Experimenting with array dimensions reveals that the execution times for smaller arrays may not differ significantly. However, in the context of neural networks, where we often work with large datasets, the importance of vectorization becomes clear. Vectorization optimizes performance by leveraging efficient array operations, making it crucial for handling the computational demands of large-scale data processing.

Congratulations on completing this assignment!🥳 You can now move on to the next one.